version: 2
updates:
  # Enable version updates for npm/pnpm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '08:00'
      timezone: 'Europe/Berlin'
    target-branch: 'staging'
    open-pull-requests-limit: 10
    reviewers:
      - '@me'
    assignees:
      - '@me'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'automated'
    groups:
      # Group all dev dependencies together
      dev-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
        exclude-patterns:
          - '@types/*'
      # Group TypeScript types separately
      types-dependencies:
        patterns:
          - '@types/*'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      # Ignore major version updates for now (you can remove this if you want them)
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # Enable version updates for npm/pnpm in backend app
  - package-ecosystem: 'npm'
    directory: '/apps/backend'
    schedule:
      interval: 'daily'
      time: '08:00'
      timezone: 'Europe/Berlin'
    target-branch: 'staging'
    open-pull-requests-limit: 10
    reviewers:
      - '@me'
    assignees:
      - '@me'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'automated'
      - 'backend'
    groups:
      # Group all dev dependencies together
      dev-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
        exclude-patterns:
          - '@types/*'
      # Group TypeScript types separately
      types-dependencies:
        patterns:
          - '@types/*'
        update-types:
          - 'minor'
          - 'patch'
      # Group NestJS packages together
      nestjs-dependencies:
        patterns:
          - '@nestjs/*'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # Enable version updates for npm/pnpm in frontend app
  - package-ecosystem: 'npm'
    directory: '/apps/frontend'
    schedule:
      interval: 'daily'
      time: '08:00'
      timezone: 'Europe/Berlin'
    target-branch: 'staging'
    open-pull-requests-limit: 10
    reviewers:
      - '@me'
    assignees:
      - '@me'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'automated'
      - 'frontend'
    groups:
      # Group all dev dependencies together
      dev-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
        exclude-patterns:
          - '@types/*'
      # Group TypeScript types separately
      types-dependencies:
        patterns:
          - '@types/*'
        update-types:
          - 'minor'
          - 'patch'
      # Group React packages together
      react-dependencies:
        patterns:
          - 'react*'
          - '@vitejs/*'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # Enable version updates for npm/pnpm in worker app
  - package-ecosystem: 'npm'
    directory: '/apps/worker'
    schedule:
      interval: 'daily'
      time: '08:00'
      timezone: 'Europe/Berlin'
    target-branch: 'staging'
    open-pull-requests-limit: 10
    reviewers:
      - '@me'
    assignees:
      - '@me'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'automated'
      - 'worker'
    groups:
      # Group all dev dependencies together
      dev-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
        exclude-patterns:
          - '@types/*'
      # Group TypeScript types separately
      types-dependencies:
        patterns:
          - '@types/*'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # Enable version updates for npm/pnpm in shared package
  - package-ecosystem: 'npm'
    directory: '/packages/shared'
    schedule:
      interval: 'daily'
      time: '08:00'
      timezone: 'Europe/Berlin'
    target-branch: 'staging'
    open-pull-requests-limit: 10
    reviewers:
      - '@me'
    assignees:
      - '@me'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'automated'
      - 'shared'
    groups:
      # Group all dev dependencies together
      dev-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
        exclude-patterns:
          - '@types/*'
      # Group TypeScript types separately
      types-dependencies:
        patterns:
          - '@types/*'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '08:00'
      timezone: 'Europe/Berlin'
    target-branch: 'staging'
    open-pull-requests-limit: 5
    reviewers:
      - '@me'
    assignees:
      - '@me'
    commit-message:
      prefix: 'ci'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'automated'
      - 'github-actions'
    groups:
      # Group all GitHub Actions updates together
      github-actions:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
