version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: asyncstand
      POSTGRES_PASSWORD: localpassword
      POSTGRES_DB: asyncstand_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile.railway
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: postgresql://asyncstand:localpassword@postgres:5432/asyncstand_dev
      REDIS_URL: redis://redis:6379
      JWT_SECRET: local-development-secret
      FRONTEND_URL: http://localhost:3000
      CORS_ORIGIN: http://localhost:3000
    depends_on:
      - postgres
      - redis
    command: node dist/src/main.js

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile.railway
      args:
        VITE_API_URL: http://localhost:3001
        VITE_APP_NAME: AsyncStand
        VITE_NODE_ENV: development
    ports:
      - "3000:80"
    environment:
      VITE_API_URL: http://localhost:3001
      VITE_APP_NAME: AsyncStand
      VITE_NODE_ENV: development
    depends_on:
      - backend

volumes:
  postgres_data: