# Nixpacks configuration for Railway deployment

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install -g pnpm@10.15.0",
  "export PATH=\"$PATH:$(npm prefix -g)/bin\"",
  "$(npm prefix -g)/bin/pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["$(npm prefix -g)/bin/pnpm build"]

[start]
cmd = "$(npm prefix -g)/bin/pnpm start:prod"

[variables]
NODE_ENV = "production"