# Nixpacks configuration for Railway deployment

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install -g pnpm@10.15.0",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm start:prod"

[variables]
NODE_ENV = "production"
NPM_CONFIG_REGISTRY = "https://registry.npmjs.org/"