# Nixpacks configuration for Railway deployment

[phases.setup]
nixPkgs = ["nodejs_20", "pnpm-10_x"]

[phases.install]
cmds = ["corepack enable", "corepack prepare pnpm@10.15.0 --activate", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm start:prod"

[variables]
NODE_ENV = "production"