[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/backend/Dockerfile.railway"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
region = "us-west1"

[[services]]
name = "backend"
dockerfilePath = "apps/backend/Dockerfile.railway"
startCommand = "node dist/src/main.js"

[[services]]
name = "frontend"
dockerfilePath = "apps/frontend/Dockerfile.railway"