services:
  # Backend API Service
  - type: web
    name: asyncstand-backend
    runtime: node
    repo: https://github.com/YOUR_GITHUB_USERNAME/asyncstand
    region: oregon # or frankfurt, singapore, ohio
    plan: free # or starter ($7/mo) for production
    buildCommand: |
      # Install pnpm
      npm install -g pnpm@10.13.1
      # Install all dependencies
      pnpm install --frozen-lockfile
      # Build shared package first
      pnpm --filter shared build
      # Generate Prisma client
      cd apps/backend && npx prisma generate
      # Build backend
      cd ../.. && pnpm --filter backend build
    startCommand: cd apps/backend && npx prisma migrate deploy && node dist/src/main.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: asyncstand-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: asyncstand-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true # Render generates a secure random value
      - key: FRONTEND_URL
        value: https://asyncstand-frontend.onrender.com

  # Frontend Static Site
  - type: web
    name: asyncstand-frontend
    runtime: static
    repo: https://github.com/YOUR_GITHUB_USERNAME/asyncstand
    buildCommand: |
      # Install pnpm
      npm install -g pnpm@10.13.1
      # Install dependencies
      pnpm install --frozen-lockfile
      # Build shared package
      pnpm --filter shared build
      # Build frontend with env vars
      cd apps/frontend && VITE_API_URL=https://asyncstand-backend.onrender.com pnpm build
    staticPublishPath: ./apps/frontend/dist
    pullRequestPreviewsEnabled: true # Optional: PR previews
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production

  # Background Worker (if needed later)
  # - type: worker
  #   name: asyncstand-worker
  #   runtime: node
  #   repo: https://github.com/YOUR_GITHUB_USERNAME/asyncstand
  #   buildCommand: pnpm install --frozen-lockfile && pnpm build
  #   startCommand: cd apps/worker && node dist/index.js

# Databases
databases:
  - name: asyncstand-db
    plan: free # 1GB free, or standard ($7/mo) for production
    ipAllowList: [] # Allow all IPs, or specify for security

# Redis
services:
  - type: redis
    name: asyncstand-redis
    plan: free # 25MB free, or starter ($10/mo) for production
    ipAllowList: []