export { LandingPage } from '@/pages/LandingPage';
export { LoginPage } from '@/pages/LoginPage';
export { SignUpPage } from '@/pages/SignUpPage';
export { OptimizedDashboardPage as DashboardPage } from '@/pages/OptimizedDashboardPage';
export { OptimizedTeamsPage as TeamsPage } from '@/pages/OptimizedTeamsPage';
export { TeamDetailPage } from '@/pages/TeamDetailPage';
export { StandupsPage } from '@/pages/StandupsPage';
export { StandupConfigPage } from '@/pages/StandupConfigPage';
export { StandupResponsePage } from '@/pages/StandupResponsePage';
export { StandupWizardPage } from '@/pages/StandupWizardPage';
export { StandupEditPage } from '@/pages/StandupEditPage';
export { StandupConfigDetailsPage } from '@/pages/StandupConfigDetailsPage';
export { NotFoundPage } from '@/pages/NotFoundPage';
export { ErrorPage } from '@/pages/ErrorPage';
