export const DEFAULT_FEATURES = [
  // Core Features
  {
    key: 'basic_standups',
    name: 'Basic Standups',
    description: 'Core standup functionality with standard questions',
    isEnabled: true,
    environment: ['development', 'staging', 'production'],
    category: 'core',
    isPlanBased: false,
    requiresAdmin: false,
  },
  {
    key: 'advanced_standups',
    name: 'Advanced Standups',
    description: 'Custom questions, templates, and advanced scheduling',
    isEnabled: true,
    environment: ['development', 'staging', 'production'],
    category: 'core',
    isPlanBased: true,
    requiresAdmin: false,
  },

  // Analytics Features
  {
    key: 'basic_analytics',
    name: 'Basic Analytics',
    description: 'Basic reporting and team insights',
    isEnabled: true,
    environment: ['development', 'staging', 'production'],
    category: 'analytics',
    isPlanBased: true,
    requiresAdmin: false,
  },
  {
    key: 'advanced_analytics',
    name: 'Advanced Analytics',
    description: 'Detailed insights, trends, and custom reports',
    isEnabled: true,
    environment: ['development', 'staging', 'production'],
    category: 'analytics',
    isPlanBased: true,
    requiresAdmin: false,
  },

  // Integration Features
  {
    key: 'slack_integration',
    name: 'Slack Integration',
    description: 'Slack bot and notifications',
    isEnabled: true,
    environment: ['development', 'staging', 'production'],
    category: 'integration',
    isPlanBased: false,
    requiresAdmin: true,
  },
  {
    key: 'teams_integration',
    name: 'Microsoft Teams Integration',
    description: 'Microsoft Teams bot and notifications',
    isEnabled: false, // Not yet implemented
    environment: ['development'],
    category: 'integration',
    isPlanBased: true,
    requiresAdmin: true,
  },
  {
    key: 'webhook_integrations',
    name: 'Webhook Integrations',
    description: 'Custom webhook endpoints for external integrations',
    isEnabled: true,
    environment: ['development', 'staging', 'production'],
    category: 'integration',
    isPlanBased: true,
    requiresAdmin: true,
  },
  {
    key: 'api_access',
    name: 'API Access',
    description: 'REST API access for custom integrations',
    isEnabled: true,
    environment: ['development', 'staging', 'production'],
    category: 'integration',
    isPlanBased: true,
    requiresAdmin: false,
  },

  // Customization Features
  {
    key: 'custom_branding',
    name: 'Custom Branding',
    description: 'Custom logo, colors, and theming',
    isEnabled: true,
    environment: ['development', 'staging', 'production'],
    category: 'customization',
    isPlanBased: true,
    requiresAdmin: true,
  },
  {
    key: 'white_labeling',
    name: 'White Labeling',
    description: 'Remove AsyncStand branding completely',
    isEnabled: true,
    environment: ['development', 'staging', 'production'],
    category: 'customization',
    isPlanBased: true,
    requiresAdmin: true,
  },

  // Support Features
  {
    key: 'priority_support',
    name: 'Priority Support',
    description: 'Faster response times and dedicated support channel',
    isEnabled: true,
    environment: ['development', 'staging', 'production'],
    category: 'support',
    isPlanBased: true,
    requiresAdmin: false,
  },

  // Experimental Features
  {
    key: 'ai_insights',
    name: 'AI Insights',
    description: 'AI-powered standup analysis and recommendations',
    isEnabled: false,
    environment: ['development'],
    category: 'experimental',
    isPlanBased: false,
    requiresAdmin: false,
    rolloutType: 'percentage',
    rolloutValue: { percentage: 10 }, // 10% rollout
  },
  {
    key: 'new_ui',
    name: 'New UI Design',
    description: 'Beta version of the new user interface',
    isEnabled: true,
    environment: ['development', 'staging'],
    category: 'experimental',
    isPlanBased: false,
    requiresAdmin: false,
    rolloutType: 'org_list',
    rolloutValue: { orgIds: [] }, // Add specific org IDs for testing
  },
  {
    key: 'mobile_app',
    name: 'Mobile App Access',
    description: 'Access to mobile application (iOS/Android)',
    isEnabled: false,
    environment: ['development'],
    category: 'experimental',
    isPlanBased: true,
    requiresAdmin: false,
  },

  // Billing Features
  {
    key: 'billing_portal',
    name: 'Billing Portal',
    description: 'Access to billing and subscription management',
    isEnabled: true,
    environment: ['development', 'staging', 'production'],
    category: 'billing',
    isPlanBased: false,
    requiresAdmin: true,
  },
  {
    key: 'invoice_management',
    name: 'Invoice Management',
    description: 'Download and manage invoices',
    isEnabled: true,
    environment: ['development', 'staging', 'production'],
    category: 'billing',
    isPlanBased: true,
    requiresAdmin: true,
  },
];

export const DEFAULT_PLANS = [
  {
    key: 'free',
    name: 'Free Plan',
    displayName: 'Free',
    description: 'Perfect for small teams getting started',
    price: 0,
    interval: 'month',
    stripePriceId: null,
    isActive: true,
    sortOrder: 0,
    memberLimit: 5,
    teamLimit: 2,
    standupLimit: 50, // per month
    storageLimit: 100, // MB
    integrationLimit: 1,
    features: [
      { featureKey: 'basic_standups', enabled: true },
      { featureKey: 'slack_integration', enabled: true },
      { featureKey: 'basic_analytics', enabled: false },
    ],
  },
  {
    key: 'starter',
    name: 'Starter Plan',
    displayName: 'Starter',
    description: 'For growing teams that need more features',
    price: 999, // $9.99 in cents
    interval: 'month',
    stripePriceId: 'price_starter_monthly', // Replace with actual Stripe price ID
    isActive: true,
    sortOrder: 1,
    memberLimit: 25,
    teamLimit: 10,
    standupLimit: 500,
    storageLimit: 1000,
    integrationLimit: 3,
    features: [
      { featureKey: 'basic_standups', enabled: true },
      { featureKey: 'advanced_standups', enabled: true },
      { featureKey: 'slack_integration', enabled: true },
      { featureKey: 'basic_analytics', enabled: true },
      { featureKey: 'webhook_integrations', enabled: true },
    ],
  },
  {
    key: 'professional',
    name: 'Professional Plan',
    displayName: 'Professional',
    description: 'For teams that need advanced features and insights',
    price: 2999, // $29.99 in cents
    interval: 'month',
    stripePriceId: 'price_professional_monthly', // Replace with actual Stripe price ID
    isActive: true,
    sortOrder: 2,
    memberLimit: 100,
    teamLimit: 50,
    standupLimit: 2000,
    storageLimit: 5000,
    integrationLimit: 10,
    features: [
      { featureKey: 'basic_standups', enabled: true },
      { featureKey: 'advanced_standups', enabled: true },
      { featureKey: 'slack_integration', enabled: true },
      { featureKey: 'basic_analytics', enabled: true },
      { featureKey: 'advanced_analytics', enabled: true },
      { featureKey: 'webhook_integrations', enabled: true },
      { featureKey: 'api_access', enabled: true },
      { featureKey: 'custom_branding', enabled: true },
      { featureKey: 'priority_support', enabled: true },
      { featureKey: 'invoice_management', enabled: true },
    ],
  },
  {
    key: 'enterprise',
    name: 'Enterprise Plan',
    displayName: 'Enterprise',
    description: 'For large organizations with custom needs',
    price: 9999, // $99.99 in cents - base price, usually custom
    interval: 'month',
    stripePriceId: 'price_enterprise_monthly', // Replace with actual Stripe price ID
    isActive: true,
    sortOrder: 3,
    memberLimit: null, // unlimited
    teamLimit: null,
    standupLimit: null,
    storageLimit: null,
    integrationLimit: null,
    features: [
      { featureKey: 'basic_standups', enabled: true },
      { featureKey: 'advanced_standups', enabled: true },
      { featureKey: 'slack_integration', enabled: true },
      { featureKey: 'teams_integration', enabled: true },
      { featureKey: 'basic_analytics', enabled: true },
      { featureKey: 'advanced_analytics', enabled: true },
      { featureKey: 'webhook_integrations', enabled: true },
      { featureKey: 'api_access', enabled: true },
      { featureKey: 'custom_branding', enabled: true },
      { featureKey: 'white_labeling', enabled: true },
      { featureKey: 'priority_support', enabled: true },
      { featureKey: 'invoice_management', enabled: true },
      { featureKey: 'billing_portal', enabled: true },
    ],
  },
];
