export enum ErrorCode {
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  INTERNAL = 'INTERNAL',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_PASSWORD_FORMAT = 'INVALID_PASSWORD_FORMAT',
  ORG_ID_REQUIRED = 'ORG_ID_REQUIRED',
  NO_ACTIVE_ORGANIZATION = 'NO_ACTIVE_ORGANIZATION',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_ALREADY_USED = 'TOKEN_ALREADY_USED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVITE_TOKEN_INVALID = 'INVITE_TOKEN_INVALID',
  INVITE_TOKEN_EXPIRED = 'INVITE_TOKEN_EXPIRED',
  INVITE_ALREADY_ACCEPTED = 'INVITE_ALREADY_ACCEPTED',
  DUPLICATE_ORG_MEMBER = 'DUPLICATE_ORG_MEMBER',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  USER_SUSPENDED = 'USER_SUSPENDED',
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  CONFIGURATION_ERROR = 'CONFIGURATION_ERROR',
  STANDUP_CONFIG_NOT_FOUND = 'STANDUP_CONFIG_NOT_FOUND',
  STANDUP_CONFIG_ALREADY_EXISTS = 'STANDUP_CONFIG_ALREADY_EXISTS',
  INVALID_SCHEDULE = 'INVALID_SCHEDULE',
  INVALID_TIMEZONE = 'INVALID_TIMEZONE',
  INVALID_QUESTIONS = 'INVALID_QUESTIONS',
  TEAM_MEMBER_NOT_FOUND = 'TEAM_MEMBER_NOT_FOUND',
  INVALID_TIME_FORMAT = 'INVALID_TIME_FORMAT',
}

export interface ApiErrorPayload {
  code: ErrorCode;
  message: string;
  details?: unknown;
  requestId?: string;
}
