name: Frontend Tests

on:
  push:
    paths:
      - 'apps/frontend/**'
      - 'packages/**'
      - '.github/workflows/frontend-tests.yml'
      - 'pnpm-lock.yaml'
  pull_request:
    paths:
      - 'apps/frontend/**'
      - 'packages/**'
      - '.github/workflows/frontend-tests.yml'
      - 'pnpm-lock.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm -w install --frozen-lockfile

      - name: Typecheck
        run: pnpm --filter ./apps/frontend typecheck

      - name: Lint
        run: pnpm --filter ./apps/frontend lint

      - name: Run unit tests
        env:
          CI: true
        run: pnpm --filter ./apps/frontend test:run
